#pragma once

#define SERVICE_IP "@OFFLINEMOD_IP@"
#define SERVICE_IP_W L"@OFFLINEMOD_IP@"
#define SERVICE_PORT @OFFLINEMOD_PORT@
#define SERVICE_DISABLE_HTTPS @OFFLINEMOD_DISABLE_HTTPS@
#define FPS_CAP @OFFLINEMOD_FPS_CAP@
#define FPS_CAP_DIAG @OFFLINEMOD_FPS_CAP_DIAG@
